name: python-socket-example
description: Chute that demonstrates using a TCP socket in Python.
version: 1
services:
  main:
    command: python2 -u server.py
    image: python2
    source: .
    type: light
    requests:
      port-bindings:
        "8081": 8081
